# Creating Numpy array

In [1]:
import numpy as np

In [2]:
a = np.array([1 , 2 , 3])
print("Array a:", a)

Array a: [1 2 3]


In [3]:
# Create array with evenly spaced values
b = np.arange(0,10,2) # values from 0 to 10 with step 1
print("Array b:", b)

Array b: [0 2 4 6 8]


In [4]:
# Create an array filled with zeros
c = np.zeros((2,3)) #2x3 array of zeros
print("Array c: \n", c)

Array c: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
c = np.zeros((2,3),dtype = int)
print("Array c: \n", c)

Array c: 
 [[0 0 0]
 [0 0 0]]


In [6]:
# Create an array filled with ones
d = np.ones((3,2),dtype = int) #3x2 array of ones
print("Array d: \n", d)

Array d: 
 [[1 1]
 [1 1]
 [1 1]]


In [7]:
# Create an identity matrix
e = np.eye(4,dtype = int) #4x4 indentity matrix
print("Identity Matrix f: \n", e)

Identity Matrix f: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Array Manipulation functions

In [8]:
# Reshapes an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1 , (1,3)) # Reshape to 1x3
print("Reshaped array : ",reshaped)

Reshaped array :  [[1 2 3]]


In [9]:
# Reshapes an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1 , (3,1)) # Reshape to 1x3
print("Reshaped array : ",reshaped)

Reshaped array :  [[1]
 [2]
 [3]]


In [10]:
# Flatten an array
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1) #Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [11]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1) # Transpose the array
print("Transposed array : \n",transposed)

Transposed array : 
 [[1 3]
 [2 4]]


In [12]:
# Stack array vertically
a2 = np.array([1 , 2])
b2 = np.array([3 , 4])
stacked = np.vstack([a2 , b2]) #stack a and b vertically
print("Stacked array: \n", stacked)

Stacked array: 
 [[1 2]
 [3 4]]


In [13]:
np.array([10,20,30,40,50]) #1d array

array([10, 20, 30, 40, 50])

In [14]:
type(np.array([10,20,30,40,50]))

numpy.ndarray

In [15]:
a = np.array([10, 20, 30, 40, 50])

In [16]:
print(a) #vector

[10 20 30 40 50]


In [17]:
type(a)


numpy.ndarray

In [18]:
# 2D Array (Matrix)

arr = np.array([[10,20,30],[40,50,60]])
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
# 3D Array-- # Tensor

np.array([[10,20,30],[40,50,60],[70,80,90]])

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# dtype

In [20]:
np.array([11,22,33] , dtype = float)

array([11., 22., 33.])

In [21]:
np.array([11,22,33] , dtype = bool)

array([ True,  True,  True])

In [22]:
np.array([11,22,33] , dtype = complex)

array([11.+0.j, 22.+0.j, 33.+0.j])

# Numpy Arrays Vs Python Sequences

# Arange 

In [23]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [24]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Reshape

In [25]:
np.arange(1,31).reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [26]:
np.arange(1,31).reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [27]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Ones & Zeros

In [28]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Another Type ---> random()

In [30]:
np.random.rand(4,3)

array([[0.52022927, 0.08237421, 0.73660798],
       [0.70800065, 0.22133301, 0.45897884],
       [0.43139709, 0.81039697, 0.93975176],
       [0.67919307, 0.44773358, 0.79726398]])

In [31]:
np.random.randint((5,3))

array([2, 0], dtype=int32)

# linspace

In [32]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [33]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# Array Attibutes

In [34]:
a1 = np.arange(10) #1D array
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a2 = np.arange(12).reshape(3,4) #Matrix
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a3 = np.arange(8).reshape(2,2,2) #3d --> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# ndim

In [37]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a1.ndim

1

In [39]:
a2.ndim

2

In [40]:
a3.ndim

3

# Shape

In [41]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
a3.size #it has 8 items . like shape : 2,2,2 = 8

8

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a2.size

12

# item size

In [45]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a1.itemsize

8

In [47]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2.itemsize

8

In [49]:
a3.itemsize

8

In [50]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


# changing data type

In [51]:
x = np.array([33,22,2.5])
x

array([33. , 22. ,  2.5])

In [52]:
print(x.dtype)

float64


In [53]:
x.astype(int)

array([33, 22,  2])

# Array Operation

In [54]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)

In [55]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Scaler Operation

In [57]:
# Arithmetic
z1 + 5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
# Substraction
z1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [59]:
# Multiplication
z1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [60]:
z1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [61]:
# modulo
z1 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

# Relational Operator

In [62]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
z2 > 2 # if 2 is greater than everthing gives true

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

# Vector Operation

In [65]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
# Arithmetic 
z1 + z2 # both numpy array is same , we can add item wise

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [68]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [69]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [70]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

# Array Functions

In [71]:
k1 = np.random.random((3 ,3,))
k1 = np.round(k1 * 100)

In [72]:
k1

array([[19., 68., 77.],
       [82., 14., 80.],
       [54., 12., 76.]])

In [73]:
# Max
np.max(k1)

np.float64(82.0)

In [74]:
# Min
np.min(k1)

np.float64(12.0)

In [75]:
# Sum
np.sum(k1)

np.float64(482.0)

In [76]:
# prod ---> multiplication

np.prod(k1)

np.float64(449959796858880.0)

In [77]:
# if we want maxium of every row
np.max(k1 , axis = 1)

array([77., 82., 76.])

In [78]:
# maximum of every column
np.max(k1 , axis = 0)

array([82., 68., 80.])

# Statistics related functins

In [79]:
# mean
k1

array([[19., 68., 77.],
       [82., 14., 80.],
       [54., 12., 76.]])

In [80]:
np.mean(k1)

np.float64(53.55555555555556)

In [81]:
# mean of every row
k1.mean(axis = 1)

array([54.66666667, 58.66666667, 47.33333333])

In [82]:
# mean of every column
k1.mean(axis = 0)

array([51.66666667, 31.33333333, 77.66666667])

In [83]:
# median
np.median(k1)

np.float64(68.0)

In [84]:
# Standard deviation

np.std(k1)

np.float64(28.394487380127977)

In [85]:
np.std(k1 , axis = 0)

array([25.77250904, 25.94010194,  1.69967317])

In [86]:
# Variance
np.var(k1)

np.float64(806.246913580247)

# Trigonometry function

In [87]:
np.sin(k1)

array([[ 0.14987721, -0.89792768,  0.99952016],
       [ 0.31322878,  0.99060736, -0.99388865],
       [-0.55878905, -0.53657292,  0.56610764]])

In [88]:
np.cos(k1)

array([[ 0.98870462,  0.44014302, -0.03097503],
       [ 0.9496777 ,  0.13673722, -0.11038724],
       [-0.82930983,  0.84385396,  0.82433133]])

In [89]:
np.tan(k1)

array([[  0.15158947,  -2.0400816 , -32.26857578],
       [  0.32982641,   7.24460662,   9.00365495],
       [  0.6738001 ,  -0.63585993,   0.68674769]])

# Dot Product

In [90]:
s2 = np.arange(12).reshape(3,4)
s3 = np.arange(12,24).reshape(4,3)

In [91]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

# Log and Exponents

In [93]:
np.exp(s2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

# Round / Floor / Ceil

In [94]:
# round to the nearest integer
arr = np.array([1.2 , 2.7 , 3.5 , 4.9])
round_arr = np.round(arr)
print("round of arr is =", round_arr)

round of arr is = [1. 3. 4. 5.]


In [95]:
# round to two decimals
arr = np.array([1.234 , 2.567 , 3.891])
rounded_arr = np.round(arr, decimals = 2)

In [96]:
print(rounded_arr)

[1.23 2.57 3.89]


In [97]:
# randomly
np.round(np.random.random((2,3))*100)

array([[67., 66., 62.],
       [16., 96., 90.]])

In [98]:
# floor operation
arr = np.array([1.2 , 2.7 , 3.5 ,4.9])
floored_arr = np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [99]:
np.floor(np.random.random((2,3))*100) #gives the samllest integer ex : 6.8 = 6

array([[85., 93., 21.],
       [59., 95.,  9.]])

In [100]:
# Ceil operation
arr1 = np.array([1.2 , 2.7 , 3.5 , 4.9])
ceil_arr = np.ceil(arr)
print(ceil_arr)

[2. 3. 4. 5.]


In [101]:
np.ceil(np.random.random((2,3)) * 100) # gives highest integer ex : 7.8 = 8

array([[ 5., 60., 44.],
       [79., 75., 73.]])

# Indexing and Slicing

In [102]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [103]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [106]:
#  indexing on 1D array
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
p1[-1]

np.int64(9)

In [108]:
p1[0]

np.int64(0)

In [109]:
# indexing on 2D array
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
p2[1,3]

np.int64(7)

In [111]:
p2[2,3]

np.int64(11)

In [112]:
p2[1,0]

np.int64(4)

In [113]:
# indexing on 3D
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [114]:
p3[1,0,1]

np.int64(5)

In [115]:
p3[0,1,0]

np.int64(2)

In [116]:
p3[0,0,0]

np.int64(0)

In [117]:
p3[1,1,0]

np.int64(6)

# Slicing

In [119]:
# Slicing on 1D
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
p1[2:5] # fecth -2,3,4

array([2, 3, 4])

In [123]:
p1[2:5:2]

array([2, 4])

In [124]:
# Slicing on 2D
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
p2[0, :] # fecth first column

array([0, 1, 2, 3])

In [127]:
p2[:,2] # fecth total third column

array([ 2,  6, 10])

In [128]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
p2[1:3,1:3] # fecth 5,6 and 9,10

array([[ 5,  6],
       [ 9, 10]])

In [130]:
p2[::2,::3] # fecth 0,3 and 8,11

array([[ 0,  3],
       [ 8, 11]])

In [132]:
p2[::2,1::2] # fetch 1,3 and 9,11

array([[ 1,  3],
       [ 9, 11]])

In [141]:
p2[1,::3] # fecth 4,7

array([4, 7])

In [142]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
p2[:2:,1:4] # fetch 1,2,3 and 5,6,7

array([[1, 2, 3],
       [5, 6, 7]])

In [147]:
p2[:2,1:4:2] # fetch 1,3 and 5,7

array([[1, 3],
       [5, 7]])

In [152]:
p3 = np.arange(27).reshape(3,3,3)
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [155]:
p3[1] # fetch second matrix

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [157]:
p3[0:3:2] # fetch first and last

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [158]:
p3[0,1] # fetch 3,4,5

array([3, 4, 5])

In [159]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [162]:
p3[1,:,1] # fetch 10,13,16

array([10, 13, 16])

In [164]:
p3[2,1: ,1:3] # fetch array  --> 22,23,25,26

array([[22, 23],
       [25, 26]])

In [165]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [167]:
p3[0::2,0:1,0::2] # fetch - 0,2,18,20

array([[[ 0,  2]],

       [[18, 20]]])

# Iterating 

In [168]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
# Looping on 1D array
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [170]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
# looping on 2D array
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [172]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [177]:
# Looping on 3D array
for i in p3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


# Rehshaping

In [178]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [179]:
# Trnaspose

np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [180]:
p2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [181]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [182]:
p3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [183]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
# Converting any dimension to 1D
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [185]:
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [186]:
p3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [192]:
# Horizontal stacking

w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

In [193]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [195]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [196]:
# Vertical Stacking

w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [197]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [198]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [199]:
# Horizontal

w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [200]:
np.hsplit(w1,2) # splitting by 2

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [201]:
np.hsplit(w1,4) # splitting by 4

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [202]:
# Vertical Splitting
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [203]:
np.vsplit(w1,3) # splitting into 3 rows

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# Advance Indexing and Slicing

In [204]:
# Normal Indexing and Slicing

w = np.arange(12).reshape(4,3)

In [205]:
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [206]:
# Fetch 5 from array
w[1,2]

np.int64(5)

In [208]:
# fetch 4,5,7,8 from array
w[1:3,1:3]

array([[4, 5],
       [7, 8]])

# Fancy Indexing

In [209]:
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [213]:
# Fetch 1,3,4 row
w[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [214]:
# New Array

z = np.arange(24).reshape(6,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [219]:
# Fetch 1,3,4,6 rows
z[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [223]:
# Fetch 1,3,4 columns
z[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

# boolean Indexing

In [224]:
G = np.random.randint(1,100,24).reshape(6,4)

In [225]:
G

array([[79, 16, 31, 71],
       [15, 62,  3,  3],
       [16, 74, 27, 65],
       [39, 95, 91,  3],
       [15, 97, 29, 65],
       [17, 52, 49, 45]], dtype=int32)

In [226]:
# finds all numbers greater than 50
G>50

array([[ True, False, False,  True],
       [False,  True, False, False],
       [False,  True, False,  True],
       [False,  True,  True, False],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [227]:
G[G>50]

array([79, 71, 62, 74, 65, 95, 91, 97, 65, 52], dtype=int32)

In [229]:
# find out even numbers
G % 2 == 0

array([[False,  True, False, False],
       [False,  True, False, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [230]:
G[G%2==0]

array([16, 62, 16, 74, 52], dtype=int32)

In [236]:
# find all numbers greater greater than 50 and are even
(G>50) & (G%2==0)

array([[False, False, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [237]:
G[(G>50) & (G%2==0)]

array([62, 74, 52], dtype=int32)

In [238]:
# find all number not divisible by 7
G % 7 != 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [242]:
G[G % 7 != 0]

array([79, 16, 31, 71, 15, 62,  3,  3, 16, 74, 27, 65, 39, 95,  3, 15, 97,
       29, 65, 17, 52, 45], dtype=int32)

# Broadcasting

In [244]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [245]:
print(a+b)

[[ 6  8 10]
 [12 14 16]]


In [246]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


In [247]:
print(a+b)

[[0 2 4]
 [3 5 7]]


In [250]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a) 
print('\n',b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [0 1 2]


In [251]:
print(a+b) # Arithmetic Operation

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [252]:
# could not Broadcast
a = np.arange(12).reshape(3,4)
b = np.arange(3) 

print(a)
print('\n',b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [0 1 2]


In [254]:
print(a+b) # could not broadcast

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [255]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a) 
print('\n',b)

[[0 1 2]]

 [[0]
 [1]
 [2]]


In [256]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [258]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1) 

print(a)
print('\n',b)

[[0 1 2]]

 [[0]
 [1]
 [2]
 [3]]


In [259]:
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [260]:
a = np.array([1])
b = np.arange(4).reshape(2,2) 

print(a)
print('\n',b)

[1]

 [[0 1]
 [2 3]]


In [261]:
print(a+b)

[[1 2]
 [3 4]]


In [262]:
# doesnt work
a = np.arange(12).reshape(3,4) 
b = np.arange(12).reshape(4,3) 
 
print(a) 
print(b) 
 
print(a+b) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [263]:
# Not Work 
a = np.arange(16).reshape(4,4) 
b = np.arange(4).reshape(2,2) 
 
print(a) 
print(b) 
 
print(a+b) 


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

# Working with mathematical formulas

In [265]:
k = np.arange(10)

In [266]:
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [267]:
np.sum(k)

np.int64(45)

In [268]:
np.sin(k)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])